"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Copy, History, LayoutDashboard, LocateFixed, MapPin, MoreHorizontal, Pencil, Plus, Save, Settings2, ShieldCheck, Sparkles, X } from "lucide-react";
import { hasSupabase, supabase } from "@/lib/supabase";
import { Switch } from "@/components/ui/switch";

type Tab = "overview" | "schedule" | "approvals" | "payroll" | "checkin" | "settings";
const money = (value:number) => new Intl.NumberFormat("vi-VN").format(value)+"đ";
const team = [
  { name:"Nga", initials:"NG", shift:"10:00 — 18:00", time:"10:02", status:"Đang làm", tone:"green", pay:3960000 },
  { name:"Tiên", initials:"TN", shift:"08:00 — 16:00", time:"08:11", status:"Trễ 11p", tone:"amber", pay:3280000 },
  { name:"Uyên", initials:"UY", shift:"12:00 — 16:00", time:"11:58", status:"Đang làm", tone:"green", pay:2740000 },
  { name:"Thảo", initials:"TH", shift:"17:30 — 21:30", time:"—", status:"Chưa đến ca", tone:"gray", pay:2860500 },
];
const scheduleDays = [
  { short:"T2", date:"14/9" }, { short:"T3", date:"15/9" }, { short:"T4", date:"16/9", today:true },
  { short:"T5", date:"17/9" }, { short:"T6", date:"18/9" }, { short:"T7", date:"19/9" }, { short:"CN", date:"20/9" },
];
const scheduleSeed:Record<string,string[]> = {
  Nga:["10:00–18:00","10:00–18:00","10:00–18:00","16:00–21:30","10:00–18:00","OFF","OFF"],
  Tiên:["08:00–12:00","12:00–16:00","08:00–16:00","OFF","08:00–12:00","12:00–21:30","OFF"],
  Uyên:["OFF","17:30–21:30","12:00–16:00","11:30–21:30","OFF","11:30–17:30","17:30–21:30"],
  Thảo:["17:30–21:30","OFF","17:30–21:30","12:00–16:00","16:00–21:30","08:00–16:00","11:30–21:30"],
};
const initialApprovals = [
  { id:1, employee:"Tiên", kind:"Đi trễ 11 phút", date:"16/09 · Ca 08:00–16:00", reason:"Xe hư trên đường, em có báo nhóm lúc 7:48.", value:"Giữ đủ giờ công" },
  { id:2, employee:"Nga", kind:"Thiếu check-out", date:"15/09 · Ca 10:00–18:00", reason:"Quên bấm checkout, thực tế kết thúc lúc 18:05.", value:"Đề nghị 18:05" },
  { id:3, employee:"Uyên", kind:"OT 2 giờ", date:"14/09 · Ca 12:00–16:00", reason:"Ở lại hoàn thiện đơn cưới theo yêu cầu.", value:"120 phút OT" },
];

export default function Home() {
  const [tab,setTab]=useState<Tab>("overview");
  const [approvals,setApprovals]=useState(initialApprovals);
  const [toast,setToast]=useState("");
  const [checkedIn,setCheckedIn]=useState(false);
  const [locating,setLocating]=useState(false);
  const [liveFund,setLiveFund]=useState(12840500);
  const approvedCount=initialApprovals.length-approvals.length;
  const pendingAmount=Math.max(0,840000-approvedCount*210000);
  useEffect(()=>{ if(!hasSupabase||!supabase)return; const channel=supabase.channel("meehoa-live").on("postgres_changes",{event:"*",schema:"public",table:"payroll_lines"},()=>setToast("Quỹ lương vừa được cập nhật")).subscribe(); return()=>{void supabase?.removeChannel(channel)}; },[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)},[toast]);
  const title=useMemo(()=>({overview:"Tổng quan",schedule:"Lịch tuần",approvals:"Cần duyệt",payroll:"Bảng lương",checkin:"Chấm công",settings:"Cài đặt"})[tab],[tab]);
  const decide=(id:number,approved:boolean)=>{setApprovals(v=>v.filter(x=>x.id!==id));if(approved)setLiveFund(v=>v+210000);setToast(approved?"Đã duyệt và cập nhật Payable":"Đã từ chối yêu cầu")};
  const checkIn=()=>{setLocating(true);const done=()=>{setLocating(false);setCheckedIn(true);setToast("Check-in thành công lúc 10:02")};if(navigator.geolocation)navigator.geolocation.getCurrentPosition(done,done,{enableHighAccuracy:true,timeout:5000});else done()};
  const tabs:[Tab,string,typeof LayoutDashboard][]=[["overview","Tổng quan",LayoutDashboard],["schedule","Lịch",CalendarDays],["approvals","Duyệt",ShieldCheck],["payroll","Lương",CircleDollarSign],["checkin","Chấm công",MapPin],["settings","Cài đặt",Settings2]];

  return <main className="min-h-screen bg-background pb-24 text-foreground sm:pb-8">
    <header className="sticky top-0 z-20 border-b bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><button onClick={()=>setTab("overview")} className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-sm font-bold text-primary-foreground">M</div><div className="text-left"><p className="text-sm font-bold tracking-tight">MEEHOA TIME</p><p className="text-[11px] text-muted-foreground">Vận hành nhẹ nhàng</p></div></button><div className="hidden items-center gap-1 sm:flex">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold ${tab===id?"bg-secondary text-primary":"text-muted-foreground hover:bg-muted"}`}><Icon className="size-4"/>{label}</button>)}</div><button className="grid size-9 place-items-center rounded-full border bg-card" aria-label="Tùy chọn"><MoreHorizontal className="size-4"/></button></div></header>
    <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-9">
      <div className="mb-6 flex items-end justify-between"><div><p className="eyebrow">Hôm nay · Thứ Tư, 16/09</p><h1 className="mt-1 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">{title}</h1></div><div className="hidden items-center gap-2 rounded-full border bg-card px-3 py-2 text-xs font-semibold md:flex"><span className="size-2 rounded-full bg-emerald-500"/>{hasSupabase?"Supabase Realtime":"Chế độ demo"}</div></div>

      {tab==="overview"&&<Overview fund={liveFund} pending={pendingAmount} pendingCount={approvals.length} onNavigate={setTab}/>} 
      {tab==="schedule"&&<Schedule/>}
      {tab==="approvals"&&<Approvals items={approvals} decide={decide}/>} 
      {tab==="payroll"&&<Payroll fund={liveFund} pending={pendingAmount}/>} 
      {tab==="checkin"&&<Checkin checkedIn={checkedIn} locating={locating} onCheckIn={checkIn}/>} 
      {tab==="settings"&&<Settings onSaved={message=>setToast(message)}/>} 
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-20 border-t bg-background/95 backdrop-blur-xl sm:hidden"><div className="mx-auto grid max-w-lg grid-cols-6 px-1 py-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex flex-col items-center gap-1 rounded-xl py-1.5 text-[9px] font-semibold ${tab===id?"text-primary":"text-muted-foreground"}`}><Icon className="size-4"/>{label}{id==="approvals"&&approvals.length>0&&<span className="absolute ml-5 -mt-1 grid size-4 place-items-center rounded-full bg-amber-500 text-[8px] text-white">{approvals.length}</span>}</button>)}</div></nav>
    {toast&&<output className="fixed bottom-24 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-full bg-[#17231d] px-4 py-3 text-xs font-semibold text-white shadow-xl sm:bottom-8"><CheckCircle2 className="size-4 text-emerald-400"/>{toast}</output>}
  </main>;
}

function Overview({fund,pending,pendingCount,onNavigate}:{fund:number;pending:number;pendingCount:number;onNavigate:(t:Tab)=>void}){return <><section className="payroll-card overflow-hidden rounded-[28px] p-6 text-white shadow-2xl shadow-emerald-950/15 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-emerald-100/75">Quỹ lương · Tháng 09</p><p className="mt-3 text-4xl font-bold tracking-[-.05em] sm:text-5xl">{money(fund)}</p><p className="mt-2 text-sm text-emerald-50/75">Đã phát sinh theo Payable được xác nhận</p></div><div className="grid size-11 place-items-center rounded-2xl bg-white/12"><Sparkles className="size-5"/></div></div><div className="mt-7 grid grid-cols-2 gap-3 border-t border-white/15 pt-5"><div><p className="text-xs text-emerald-100/65">Đang chờ xử lý</p><p className="mt-1 text-lg font-bold">{money(pending)}</p></div><div><p className="text-xs text-emerald-100/65">Dự kiến cuối tháng</p><p className="mt-1 text-lg font-bold">24.600.000đ</p></div></div></section><section className="mt-4 grid grid-cols-3 gap-3">{[["8","Có lịch"],["5","Đang làm"],[String(pendingCount),"Cần chú ý"]].map(([v,l],i)=><button onClick={()=>i===2&&onNavigate("approvals")} key={l} className="rounded-2xl border bg-card p-4 text-left"><p className={`text-2xl font-bold ${i===2?"text-amber-600":""}`}>{v}</p><p className="mt-1 text-xs text-muted-foreground">{l}</p></button>)}</section><section className="mt-8"><SectionTitle eyebrow="Nhân sự hôm nay" title="Ca đang diễn ra" action="Xem lịch" onAction={()=>onNavigate("schedule")}/><div className="overflow-hidden rounded-[24px] border bg-card">{team.slice(0,3).map((p,i)=><div key={p.name} className={`flex items-center gap-3 p-4 sm:px-5 ${i?"border-t":""}`}><Avatar person={p}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-bold">{p.name}</p><Status text={p.status} tone={p.tone}/></div><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3"/>{p.shift} · vào {p.time}</p></div><MapPin className="size-4 text-muted-foreground"/></div>)}</div></section></>}
function Schedule(){
  const [grid,setGrid]=useState(scheduleSeed);
  const [editing,setEditing]=useState<{name:string;day:number}|null>(null);
  const [draft,setDraft]=useState("");
  const [saved,setSaved]=useState(false);
  const openCell=(name:string,day:number)=>{setEditing({name,day});setDraft(grid[name][day])};
  const apply=()=>{if(!editing)return;setGrid(old=>({...old,[editing.name]:old[editing.name].map((value,index)=>index===editing.day?(draft||"OFF"):value)}));setEditing(null);setSaved(false)};
  const copyPrevious=()=>{setGrid({Nga:["10:00–18:00","10:00–18:00","10:00–18:00","16:00–21:30","10:00–18:00","OFF","OFF"],Tiên:["08:00–12:00","12:00–16:00","08:00–16:00","OFF","08:00–12:00","12:00–21:30","OFF"],Uyên:["OFF","17:30–21:30","12:00–16:00","11:30–21:30","OFF","11:30–17:30","17:30–21:30"],Thảo:["17:30–21:30","OFF","17:30–21:30","12:00–16:00","16:00–21:30","08:00–16:00","11:30–21:30"]});setSaved(false)};
  return <>
    <section className="mb-4 rounded-3xl border bg-card p-3 sm:p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2"><button aria-label="Tuần trước" className="grid size-10 place-items-center rounded-xl border"><ChevronLeft className="size-4"/></button><div className="min-w-[150px] text-center"><p className="text-sm font-bold">14 — 20 tháng 9</p><p className="text-xs text-muted-foreground">Tuần này</p></div><button aria-label="Tuần sau" className="grid size-10 place-items-center rounded-xl border"><ChevronRight className="size-4"/></button></div>
        <div className="flex flex-1 justify-end gap-2"><button onClick={copyPrevious} className="flex items-center gap-2 rounded-xl border bg-background px-3 py-2.5 text-sm font-bold"><Copy className="size-4"/><span className="hidden sm:inline">Sao chép tuần trước</span><span className="sm:hidden">Sao chép</span></button><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Save className="size-4"/>{saved?"Đã lưu":"Lưu lịch"}</button></div>
      </div>
    </section>

    <div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted-foreground">Chạm vào ô để đổi ca · Vuốt ngang để xem cả tuần</p><button className="flex items-center gap-1.5 text-sm font-bold text-primary"><Plus className="size-4"/>Nhân viên</button></div>
    <section className="schedule-sheet overflow-x-auto rounded-2xl border bg-card shadow-sm">
      <table className="w-full min-w-[920px] border-collapse text-sm">
        <thead><tr><th className="sticky left-0 z-10 w-40 border-b border-r bg-[#f5f7f4] px-4 py-3 text-left text-xs font-bold text-muted-foreground">NHÂN VIÊN</th>{scheduleDays.map(day=><th key={day.date} className={`min-w-[108px] border-b border-r px-2 py-3 text-center last:border-r-0 ${day.today?"bg-emerald-50":"bg-[#f5f7f4]"}`}><span className={`block text-xs font-bold ${day.today?"text-primary":""}`}>{day.short}</span><span className="mt-0.5 block text-xs font-medium text-muted-foreground">{day.date}</span></th>)}</tr></thead>
        <tbody>{Object.entries(grid).map(([name,shifts],row)=><tr key={name}><th className="sticky left-0 z-10 border-b border-r bg-card px-4 py-3 text-left last:border-b-0"><div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-full bg-secondary text-xs font-bold">{name.slice(0,2).toUpperCase()}</span><div><span className="block font-bold">{name}</span><span className="block text-xs font-normal text-muted-foreground">{row===0?"Part-time":"Nhân viên"}</span></div></div></th>{shifts.map((shift,day)=><td key={`${name}-${day}`} className={`border-b border-r p-1.5 last:border-r-0 ${scheduleDays[day].today?"bg-emerald-50/35":""}`}><button onClick={()=>openCell(name,day)} className={`group min-h-14 w-full rounded-xl border px-2 py-2 text-center text-sm font-bold transition hover:border-primary hover:shadow-sm ${shift==="OFF"?"border-transparent bg-muted text-muted-foreground":"border-emerald-100 bg-emerald-50 text-emerald-800"}`}><span>{shift}</span><span className="mt-1 hidden text-[11px] font-medium opacity-60 group-hover:block">Chỉnh sửa</span></button></td>)}</tr>)}</tbody>
      </table>
    </section>

    <div className="mt-4 flex flex-wrap gap-2">{["08:00–12:00","12:00–16:00","16:00–21:30","17:30–21:30","11:30–21:30","OFF"].map(shift=><span key={shift} className={`rounded-lg px-3 py-2 text-xs font-semibold ${shift==="OFF"?"bg-muted text-muted-foreground":"bg-emerald-50 text-emerald-800"}`}>{shift}</span>)}</div>

    {editing&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-0 sm:items-center sm:p-4" onMouseDown={event=>{if(event.target===event.currentTarget)setEditing(null)}}><section role="dialog" aria-modal="true" aria-label="Chỉnh ca làm" className="w-full max-w-md rounded-t-[28px] bg-card p-5 shadow-2xl sm:rounded-[28px]"><div className="flex items-start justify-between"><div><p className="eyebrow">Chỉnh ca làm</p><h2 className="mt-1 text-xl font-bold">{editing.name} · {scheduleDays[editing.day].short} {scheduleDays[editing.day].date}</h2></div><button onClick={()=>setEditing(null)} aria-label="Đóng" className="grid size-9 place-items-center rounded-full bg-muted"><X className="size-4"/></button></div><div className="mt-5 grid grid-cols-2 gap-2">{["08:00–12:00","12:00–16:00","16:00–21:30","17:30–21:30","11:30–21:30","OFF"].map(shift=><button key={shift} onClick={()=>setDraft(shift)} className={`rounded-xl border px-3 py-3 text-sm font-bold ${draft===shift?"border-primary bg-secondary text-primary":""}`}>{shift}</button>)}</div><label className="mt-5 block text-sm font-bold" htmlFor="custom-shift">Hoặc nhập giờ riêng</label><input id="custom-shift" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ví dụ: 10:00–18:00" className="mt-2 h-12 w-full rounded-xl border bg-background px-4 text-base outline-none focus:ring-2 focus:ring-primary/25"/><div className="mt-5 flex gap-2"><button onClick={()=>setDraft("OFF")} className="rounded-xl border px-4 py-3 text-sm font-bold">Đặt OFF</button><button onClick={apply} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><Check className="size-4"/>Áp dụng</button></div></section></div>}
  </>
}
function Approvals({items,decide}:{items:typeof initialApprovals;decide:(id:number,a:boolean)=>void}){return <>{items.length===0?<Empty/>:<div className="space-y-3">{items.map(item=><section key={item.id} className="rounded-3xl border bg-card p-5"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-700"><AlertCircle className="size-5"/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{item.employee} · {item.kind}</h2><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">Chờ duyệt</span></div><p className="mt-1 text-xs text-muted-foreground">{item.date}</p><div className="mt-4 rounded-2xl bg-muted p-4 text-sm leading-6"><p>{item.reason}</p><p className="mt-2 font-bold text-primary">{item.value}</p></div><div className="mt-4 flex gap-2"><button onClick={()=>decide(item.id,true)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-primary-foreground"><Check className="size-4"/>Duyệt</button><button onClick={()=>decide(item.id,false)} className="flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-xs font-bold"><X className="size-4"/>Từ chối</button></div></div></div></section>)}</div>}</>}
function Payroll({fund,pending}:{fund:number;pending:number}){return <><div className="grid gap-3 sm:grid-cols-3"><Metric label="Đã xác nhận" value={money(fund)} tone="green"/><Metric label="Pending" value={money(pending)} tone="amber"/><Metric label="Payroll confidence" value={pending?"Cần xử lý":"Sẵn sàng"} tone={pending?"amber":"green"}/></div><section className="mt-5 overflow-hidden rounded-3xl border bg-card"><div className="border-b p-5"><p className="eyebrow">Chi tiết tháng 09/2026</p><h2 className="mt-1 text-xl font-bold">Theo nhân viên</h2></div>{team.map((p,i)=><button key={p.name} className={`flex w-full items-center gap-3 p-4 text-left sm:px-5 ${i?"border-t":""}`}><Avatar person={p}/><div className="flex-1"><p className="font-bold">{p.name}</p><p className="mt-1 text-xs text-muted-foreground">{i===0?"158h 24p · Theo giờ":"Lương tháng · Công đã đối soát"}</p></div><div className="text-right"><p className="font-bold">{money(p.pay)}</p><p className={`mt-1 text-[10px] font-bold ${i===1?"text-amber-600":"text-emerald-600"}`}>{i===1?"2 mục pending":"Sẵn sàng"}</p></div><ChevronRight className="size-4 text-muted-foreground"/></button>)}</section><button disabled={pending>0} className="mt-4 w-full rounded-2xl bg-primary px-5 py-4 text-sm font-bold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40">{pending>0?"Xử lý hết pending để khóa lương":"Khóa bảng lương tháng 09"}</button></>}
function Checkin({checkedIn,locating,onCheckIn}:{checkedIn:boolean;locating:boolean;onCheckIn:()=>void}){return <div className="mx-auto max-w-md"><section className="rounded-[32px] border bg-card p-6 text-center shadow-sm"><div className="mx-auto grid size-16 place-items-center rounded-3xl bg-secondary text-primary"><LocateFixed className="size-7"/></div><p className="mt-6 eyebrow">Ca hôm nay</p><h2 className="mt-2 text-3xl font-bold tracking-tight">10:00 — 18:00</h2><p className="mt-2 text-sm text-muted-foreground">MEEHOA · trong phạm vi 120m</p><div className="my-6 h-px bg-border"/>{checkedIn?<><div className="rounded-2xl bg-emerald-50 p-4 text-emerald-800"><CheckCircle2 className="mx-auto size-6"/><p className="mt-2 font-bold">Đã check-in · 10:02</p><p className="mt-1 text-xs">Đang làm 03:42 · Payable đang tích lũy</p></div><button className="mt-4 w-full rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm font-bold text-rose-700">Check-out</button></>:<button onClick={onCheckIn} disabled={locating} className="w-full rounded-2xl bg-primary px-5 py-5 text-base font-bold text-primary-foreground shadow-lg shadow-emerald-900/15 disabled:opacity-60">{locating?"Đang xác minh vị trí…":"Check-in bằng GPS"}</button>}<p className="mt-4 flex items-center justify-center gap-1.5 text-[11px] text-muted-foreground"><ShieldCheck className="size-3"/>Vị trí chỉ được lưu tại thời điểm chấm công</p></section></div>}

type SalaryProfile={name:string;initials:string;type:"hourly"|"monthly";amount:number;allowance:number;effective:string};
const salarySeed:SalaryProfile[]=[
  {name:"Nga",initials:"NG",type:"hourly",amount:25000,allowance:300000,effective:"01/09/2026"},
  {name:"Tiên",initials:"TN",type:"monthly",amount:6500000,allowance:500000,effective:"01/09/2026"},
  {name:"Uyên",initials:"UY",type:"hourly",amount:28000,allowance:0,effective:"01/08/2026"},
  {name:"Thảo",initials:"TH",type:"hourly",amount:25000,allowance:200000,effective:"01/09/2026"},
];
function Settings({onSaved}:{onSaved:(message:string)=>void}){
  const [section,setSection]=useState<"salary"|"rules">("salary");
  const [profiles,setProfiles]=useState(salarySeed);
  const [editing,setEditing]=useState<number|null>(null);
  const [draft,setDraft]=useState<SalaryProfile|null>(null);
  const [rules,setRules]=useState({grace:5,rounding:"Không làm tròn",otApproval:true,holdMissing:true,geofence:true});
  const edit=(index:number)=>{setEditing(index);setDraft({...profiles[index]})};
  const saveProfile=()=>{if(editing===null||!draft)return;setProfiles(old=>old.map((profile,index)=>index===editing?draft:profile));setEditing(null);setDraft(null);onSaved("Đã lưu thiết lập lương của "+draft.name)};
  return <>
    <div className="mb-5 flex rounded-2xl bg-muted p-1"><button onClick={()=>setSection("salary")} className={`flex-1 rounded-xl px-3 py-3 text-sm font-bold ${section==="salary"?"bg-card text-primary shadow-sm":"text-muted-foreground"}`}>Nhân viên & mức lương</button><button onClick={()=>setSection("rules")} className={`flex-1 rounded-xl px-3 py-3 text-sm font-bold ${section==="rules"?"bg-card text-primary shadow-sm":"text-muted-foreground"}`}>Quy tắc chấm công</button></div>
    {section==="salary"?<>
      <div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">Áp dụng từ kỳ lương hiện tại</p><h2 className="mt-1 text-xl font-bold">Mức lương nhân viên</h2></div><button className="flex items-center gap-1.5 text-sm font-bold text-primary"><Plus className="size-4"/>Nhân viên</button></div>
      <section className="overflow-hidden rounded-3xl border bg-card">{profiles.map((profile,index)=><button key={profile.name} onClick={()=>edit(index)} className={`flex w-full items-center gap-3 p-4 text-left sm:px-5 ${index?"border-t":""}`}><Avatar person={profile}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-bold">{profile.name}</p><span className="rounded-full bg-secondary px-2 py-1 text-xs font-bold text-primary">{profile.type==="hourly"?"Theo giờ":"Lương tháng"}</span></div><p className="mt-1 text-xs text-muted-foreground">Áp dụng từ {profile.effective}{profile.allowance?` · Phụ cấp ${money(profile.allowance)}`:""}</p></div><div className="text-right"><p className="font-bold">{money(profile.amount)}{profile.type==="hourly"&&<span className="text-xs font-medium text-muted-foreground">/giờ</span>}</p><p className="mt-1 flex items-center justify-end gap-1 text-xs font-semibold text-primary"><Pencil className="size-3"/>Chỉnh</p></div></button>)}</section>
      <div className="mt-4 flex items-start gap-3 rounded-2xl border bg-card p-4"><History className="mt-0.5 size-5 shrink-0 text-primary"/><div><p className="text-sm font-bold">Lịch sử thay đổi được lưu riêng</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Mức lương mới chỉ áp dụng từ ngày hiệu lực, không làm thay đổi các kỳ lương đã khóa.</p></div></div>
    </>:<section className="space-y-3">
      <SettingCard title="Thời gian đi trễ" description="Khoảng trễ vẫn được ghi nhận nhưng chưa tạo cảnh báo."><div className="flex items-center gap-2"><input aria-label="Số phút cho phép" type="number" min="0" value={rules.grace} onChange={event=>setRules({...rules,grace:Number(event.target.value)})} className="h-11 w-20 rounded-xl border bg-background px-3 text-center font-bold"/><span className="text-sm font-semibold">phút</span></div></SettingCard>
      <SettingCard title="Làm tròn giờ công" description="Áp dụng sau khi ca đã đủ check-in và check-out."><select aria-label="Cách làm tròn giờ công" value={rules.rounding} onChange={event=>setRules({...rules,rounding:event.target.value})} className="h-11 rounded-xl border bg-background px-3 text-sm font-bold"><option>Không làm tròn</option><option>Theo 5 phút</option><option>Theo 15 phút</option></select></SettingCard>
      <SettingCard title="OT cần Admin duyệt" description="Checkout muộn không tự động làm tăng Payable."><Switch checked={rules.otApproval} onCheckedChange={checked=>setRules({...rules,otApproval:checked})}/></SettingCard>
      <SettingCard title="Giữ công khi thiếu check-in/out" description="Ca được đưa vào pending cho đến khi giải trình được xử lý."><Switch checked={rules.holdMissing} onCheckedChange={checked=>setRules({...rules,holdMissing:checked})}/></SettingCard>
      <SettingCard title="Xác minh vị trí shop" description="Kiểm tra phạm vi GPS tại thời điểm chấm công."><Switch checked={rules.geofence} onCheckedChange={checked=>setRules({...rules,geofence:checked})}/></SettingCard>
      <button onClick={()=>onSaved("Đã lưu quy tắc chấm công")} className="mt-2 flex w-full items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-4 text-sm font-bold text-primary-foreground"><Save className="size-4"/>Lưu quy tắc</button>
    </section>}
    {draft&&editing!==null&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 sm:items-center sm:p-4" onMouseDown={event=>{if(event.target===event.currentTarget){setEditing(null);setDraft(null)}}}><section role="dialog" aria-modal="true" aria-label="Thiết lập lương nhân viên" className="w-full max-w-md rounded-t-[28px] bg-card p-5 shadow-2xl sm:rounded-[28px]"><div className="flex items-start justify-between"><div><p className="eyebrow">Thiết lập lương</p><h2 className="mt-1 text-xl font-bold">{draft.name}</h2></div><button onClick={()=>{setEditing(null);setDraft(null)}} aria-label="Đóng" className="grid size-9 place-items-center rounded-full bg-muted"><X className="size-4"/></button></div><label className="mt-5 block text-sm font-bold" htmlFor="salary-type">Hình thức tính</label><select id="salary-type" value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value as SalaryProfile["type"]})} className="mt-2 h-12 w-full rounded-xl border bg-background px-4 text-base"><option value="hourly">Theo giờ</option><option value="monthly">Lương tháng</option></select><label className="mt-4 block text-sm font-bold" htmlFor="salary-amount">{draft.type==="hourly"?"Đơn giá mỗi giờ":"Lương cơ bản tháng"}</label><div className="relative mt-2"><input id="salary-amount" type="number" value={draft.amount} onChange={event=>setDraft({...draft,amount:Number(event.target.value)})} className="h-12 w-full rounded-xl border bg-background px-4 pr-12 text-base font-bold"/><span className="absolute right-4 top-3.5 text-sm text-muted-foreground">đ</span></div><label className="mt-4 block text-sm font-bold" htmlFor="allowance">Phụ cấp cố định</label><div className="relative mt-2"><input id="allowance" type="number" value={draft.allowance} onChange={event=>setDraft({...draft,allowance:Number(event.target.value)})} className="h-12 w-full rounded-xl border bg-background px-4 pr-12 text-base font-bold"/><span className="absolute right-4 top-3.5 text-sm text-muted-foreground">đ</span></div><label className="mt-4 block text-sm font-bold" htmlFor="effective-date">Ngày bắt đầu áp dụng</label><input id="effective-date" value={draft.effective} onChange={event=>setDraft({...draft,effective:event.target.value})} className="mt-2 h-12 w-full rounded-xl border bg-background px-4 text-base"/><button onClick={saveProfile} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3.5 text-sm font-bold text-primary-foreground"><Save className="size-4"/>Lưu thiết lập lương</button></section></div>}
  </>
}
function SettingCard({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="flex items-center gap-4 rounded-2xl border bg-card p-4 sm:p-5"><div className="min-w-0 flex-1"><p className="font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div>{children}</div>}
function SectionTitle({eyebrow,title,action,onAction}:{eyebrow:string;title:string;action:string;onAction:()=>void}){return <div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 text-xl font-bold tracking-tight">{title}</h2></div><button onClick={onAction} className="text-sm font-semibold text-primary">{action}</button></div>}
function Avatar({person}:{person:{initials:string}}){return <div className="grid size-11 shrink-0 place-items-center rounded-full bg-secondary text-xs font-bold">{person.initials}</div>}
function Status({text,tone}:{text:string;tone:string}){return <span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${tone==="green"?"bg-emerald-100 text-emerald-700":tone==="amber"?"bg-amber-100 text-amber-700":"bg-muted text-muted-foreground"}`}>{text}</span>}
function Metric({label,value,tone}:{label:string;value:string;tone:string}){return <div className="rounded-2xl border bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-bold ${tone==="amber"?"text-amber-600":"text-emerald-700"}`}>{value}</p></div>}
function Empty(){return <div className="rounded-3xl border bg-card p-12 text-center"><CheckCircle2 className="mx-auto size-10 text-emerald-600"/><h2 className="mt-4 text-xl font-bold">Đã xử lý hết</h2><p className="mt-2 text-sm text-muted-foreground">Không còn giải trình hoặc OT nào đang chờ.</p></div>}
